package com.wd.api.pact;

import au.com.dius.pact.provider.junit5.HttpTestTarget;
import au.com.dius.pact.provider.junit5.PactVerificationContext;
import au.com.dius.pact.provider.junit5.PactVerificationInvocationContextProvider;
import au.com.dius.pact.provider.junitsupport.Provider;
import au.com.dius.pact.provider.junitsupport.State;
import au.com.dius.pact.provider.junitsupport.loader.PactFolder;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.TestTemplate;
import org.junit.jupiter.api.extension.ExtendWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.boot.test.web.server.LocalServerPort;
import org.springframework.test.context.ActiveProfiles;
import org.springframework.test.context.bean.override.mockito.MockitoBean;
import com.wd.api.scheduler.TaskAlertScheduler;

/**
 * Provider-side Pact verification — replays the website's expected
 * interactions against a real portal-API booted on a random port and
 * verifies the actual responses match.
 *
 * Pact contract loaded from src/test/resources/pacts/, generated by
 * wd_website_nextjs/__tests__/pact/leads-contact.consumer.test.ts.
 *
 * Run: mvn -Dtest=LeadsContactPactProviderTest test
 */
@Provider("wd-portal-api")
@PactFolder("pacts")
@SpringBootTest(webEnvironment = SpringBootTest.WebEnvironment.RANDOM_PORT)
@ActiveProfiles("test")
class LeadsContactPactProviderTest {

    @LocalServerPort
    private int port;

    // application-test.yml sets `task.alerts.enabled=false` so the real
    // TaskAlertScheduler bean isn't registered, but TaskController autowires
    // it as required. Provide a no-op mock so the context loads cleanly.
    @MockitoBean
    private TaskAlertScheduler taskAlertScheduler;

    @BeforeEach
    void setTarget(PactVerificationContext context) {
        if (context != null) {
            context.setTarget(new HttpTestTarget("127.0.0.1", port, "/"));
        }
    }

    @TestTemplate
    @ExtendWith(PactVerificationInvocationContextProvider.class)
    void verifyPact(PactVerificationContext context) {
        context.verifyInteraction();
    }

    // Provider states from the consumer pact:
    @State("the portal-API is up and accepting public contact submissions")
    void portalIsAcceptingSubmissions() {
        // No setup needed — the running app already accepts /leads/contact.
    }

    @State("the portal-API rejects submissions that fail input validation")
    void portalRejectsInvalid() {
        // No setup needed — the validator is hard-wired in PublicContactRequest.
    }
}
