package com.wd.api.service;

import com.wd.api.dao.interfaces.ILeadsDAO;
import com.wd.api.dao.model.Leads;
import com.wd.api.dto.PartnershipReferralRequest;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import java.time.LocalDate;

@Service
public class LeadService {
    
    @Autowired
    private ILeadsDAO leadsDAO;
    
    /**
     * Create a lead from partnership referral
     * Note: Partnership form captures only essential fields. This method sets default values
     * for uncaptured fields to ensure lead is created with complete data structure.
     */
    @Transactional
    public Leads createLeadFromPartnershipReferral(PartnershipReferralRequest request) {
        Leads lead = new Leads();
        
        // ============ CLIENT INFORMATION (Captured from form) ============
        lead.setName(request.getClientName());
        lead.setEmail(request.getClientEmail());
        lead.setPhone(request.getClientPhone());
        lead.setWhatsappNumber(request.getClientWhatsapp());
        
        // ============ LEAD SOURCE & STATUS (Auto-set) ============
        // Lead Source - Always set as "referral_architect" for partnership referrals
        lead.setLeadSource("referral_architect");
        
        // Lead Status - Always start as "new_inquiry"
        lead.setLeadStatus("new_inquiry");
        
        // ============ CUSTOMER TYPE (Default value) ============
        // Set customer type to "individual" as default for referrals
        // This can be updated later by admin in the portal
        lead.setCustomerType("individual");
        
        // ============ PRIORITY (Default value) ============
        // Set priority to "medium" as default for partnership referrals
        // This can be updated later by admin in the portal
        lead.setPriority("medium");
        
        // ============ PROJECT INFORMATION (Captured from form) ============
        lead.setProjectType(request.getProjectType());
        lead.setProjectDescription(request.getProjectDescription());
        lead.setBudget(request.getEstimatedBudget());
        
        // ============ LOCATION INFORMATION (Captured from form) ============
        lead.setState(request.getState());
        lead.setDistrict(request.getDistrict());
        lead.setLocation(request.getLocation());
        
        // ============ UNCAPTURED FIELDS (Set to null/default) ============
        // These fields are not captured in partnership form but exist in leads table
        lead.setProjectSqftArea(null); // Not captured
        lead.setAddress(null); // Not captured
        lead.setRequirements(null); // Not captured
        lead.setAssignedTeam(""); // Empty, will be assigned by admin later
        lead.setClientRating(3); // Default 3 for partnership referrals (moderate rating)
        lead.setProbabilityToWin(50); // Default 50% for partnership referrals
        lead.setNextFollowUp(null); // Not set initially
        lead.setLastContactDate(null); // Not set initially
        lead.setLostReason(null); // Not applicable for new leads
        
        // ============ DATE OF ENQUIRY (Auto-set to current date) ============
        lead.setDateOfEnquiry(LocalDate.now());
        
        // ============ PARTNER TRACKING INFORMATION (in notes) ============
        // Include partner information in notes for tracking
        String partnerNotes = String.format(
            "Referred by Partner: %s (ID: %s, Type: %s)",
            request.getPartnerName(),
            request.getPartnerId(),
            request.getPartnershipType()
        );
        
        // Append any additional notes provided by partner
        if (request.getNotes() != null && !request.getNotes().trim().isEmpty()) {
            lead.setNotes(partnerNotes + "\n\nAdditional Notes: " + request.getNotes());
        } else {
            lead.setNotes(partnerNotes);
        }
        
        // ============ CREATE THE LEAD ============
        int result = leadsDAO.createLead(lead);
        
        if (result > 0) {
            // Return the created lead (note: lead_id will be auto-generated by database)
            return lead;
        } else {
            throw new RuntimeException("Failed to create lead from partnership referral");
        }
    }
    
    /**
     * Get lead by ID
     */
    public Leads getLeadById(String leadId) {
        return leadsDAO.getLeadById(leadId);
    }
    
    /**
     * Update lead status
     */
    @Transactional
    public boolean updateLeadStatus(String leadId, String status) {
        int result = leadsDAO.updateLeadStatus(leadId, status);
        return result > 0;
    }
    
    /**
     * Get leads by source (e.g., referral_architect)
     */
    public java.util.List<Leads> getLeadsBySource(String source) {
        return leadsDAO.getLeadsBySource(source);
    }
}
