package com.wd.api.model;

import jakarta.persistence.*;
import java.time.LocalDateTime;

/**
 * Password-reset token for a CustomerUser, generated by portal staff.
 * Stored in the shared {@code customer_password_reset_tokens} table so the
 * customer API's {@code /auth/reset-password} endpoint can validate it when
 * the customer clicks the emailed link.
 */
@Entity
@Table(name = "customer_password_reset_tokens")
public class CustomerPasswordResetToken {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    @Column(nullable = false)
    private String email;

    /** SHA-256 hash of the raw token sent to the customer. */
    @Column(name = "reset_code", nullable = false, length = 128)
    private String resetCode;

    @Column(name = "expires_at", nullable = false)
    private LocalDateTime expiresAt;

    @Column(nullable = false)
    private boolean used = false;

    @Column(name = "created_at", nullable = false, updatable = false)
    private LocalDateTime createdAt = LocalDateTime.now();

    protected CustomerPasswordResetToken() {}

    public CustomerPasswordResetToken(String email, String resetCode, LocalDateTime expiresAt) {
        this.email = email;
        this.resetCode = resetCode;
        this.expiresAt = expiresAt;
    }

    public boolean isExpired() {
        return LocalDateTime.now().isAfter(expiresAt);
    }

    // Getters
    public Long getId() { return id; }
    public String getEmail() { return email; }
    public String getResetCode() { return resetCode; }
    public LocalDateTime getExpiresAt() { return expiresAt; }
    public boolean isUsed() { return used; }
    public LocalDateTime getCreatedAt() { return createdAt; }
    public void setUsed(boolean used) { this.used = used; }
}
