-- Portal staff password reset tokens
-- Token stored as SHA-256 hash of raw UUID; only the raw UUID is sent in the email link.
-- Expiry: 30 minutes from creation.

CREATE TABLE IF NOT EXISTS portal_password_reset_tokens (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email       VARCHAR(255) NOT NULL,
    token_hash  VARCHAR(128) NOT NULL,   -- SHA-256(rawUUID) — never store raw token
    expires_at  TIMESTAMP    NOT NULL,   -- 30 min from creation
    used        BOOLEAN      NOT NULL DEFAULT FALSE,
    created_at  TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- Unique index on hash so lookup is O(1) and prevents duplicates
CREATE UNIQUE INDEX IF NOT EXISTS idx_portal_pw_reset_token_hash
    ON portal_password_reset_tokens (token_hash);

CREATE INDEX IF NOT EXISTS idx_portal_pw_reset_email
    ON portal_password_reset_tokens (email);

CREATE INDEX IF NOT EXISTS idx_portal_pw_reset_expires_at
    ON portal_password_reset_tokens (expires_at);
