-- Migration: Fix Site Reports Audit Schema and Align with BaseEntity
-- Version: V1_63 (renumbered from V1_51 to resolve duplicate version conflict)
-- Description: Renames/Migrates created_by_id to created_by_user_id (referencing portal_users),
--              adds missing audit columns, and ensures consistency with staff submission logic.

-- ============================================================================
-- 1. Correct Audit Columns and Foreign Keys
-- ============================================================================

DO $$ 
BEGIN 
    -- 1.1 Handle created_by_id rename/migrate
    IF EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='site_reports' AND column_name='created_by_id') THEN
        -- Drop the incorrect constraint to customer_users if it exists
        -- We'll search for the constraint name dynamically or try common patterns
        -- Based on previous findings, it might be named fkh0794dh3vnvjymnydp25psui7 or similar if generated by Hibernate
        -- But for safety and cleanliness, we'll just rename the column and then fix the FK.
        
        IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='site_reports' AND column_name='created_by_user_id') THEN
            ALTER TABLE site_reports RENAME COLUMN created_by_id TO created_by_user_id;
        ELSE
            -- If both exist, sync and drop old
            UPDATE site_reports SET created_by_user_id = created_by_id WHERE created_by_user_id IS NULL;
            ALTER TABLE site_reports DROP COLUMN created_by_id;
        END IF;
    END IF;

    -- 2. Add Missing BaseEntity Columns
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='site_reports' AND column_name='updated_by_user_id') THEN
        ALTER TABLE site_reports ADD COLUMN updated_by_user_id BIGINT;
    END IF;

    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='site_reports' AND column_name='deleted_at') THEN
        ALTER TABLE site_reports ADD COLUMN deleted_at TIMESTAMP;
    END IF;

    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='site_reports' AND column_name='deleted_by_user_id') THEN
        ALTER TABLE site_reports ADD COLUMN deleted_by_user_id BIGINT;
    END IF;

    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='site_reports' AND column_name='version') THEN
        ALTER TABLE site_reports ADD COLUMN version BIGINT DEFAULT 1 NOT NULL;
    END IF;
END $$;

-- ============================================================================
-- 3. Update Constraints and Data
-- ============================================================================

-- Ensure created_by_user_id has correct FK and is synced with submitted_by
ALTER TABLE site_reports DROP CONSTRAINT IF EXISTS fk_site_reports_created_by; -- Drop old if exists
ALTER TABLE site_reports ADD CONSTRAINT fk_site_reports_created_by FOREIGN KEY (created_by_user_id) REFERENCES portal_users(id);

-- Sync created_by_user_id with submitted_by for existing records
UPDATE site_reports SET created_by_user_id = submitted_by WHERE created_by_user_id IS NULL AND submitted_by IS NOT NULL;

-- If it was NOT NULL before, ensure it stays NOT NULL after syncing
-- ALTER TABLE site_reports ALTER COLUMN created_by_user_id SET NOT NULL; 

-- ============================================================================
-- 4. Add Missing Reporting Fields (Weather, Manpower, Equipment, Progress)
-- ============================================================================
DO $$ 
BEGIN 
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='site_reports' AND column_name='weather') THEN
        ALTER TABLE site_reports ADD COLUMN weather VARCHAR(100);
    END IF;

    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='site_reports' AND column_name='manpower_deployed') THEN
        ALTER TABLE site_reports ADD COLUMN manpower_deployed INTEGER;
    END IF;

    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='site_reports' AND column_name='equipment_used') THEN
        ALTER TABLE site_reports ADD COLUMN equipment_used TEXT;
    END IF;

    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='site_reports' AND column_name='work_progress') THEN
        ALTER TABLE site_reports ADD COLUMN work_progress TEXT;
    END IF;
END $$;

-- Create index for soft delete
CREATE INDEX IF NOT EXISTS idx_site_reports_deleted_at ON site_reports(deleted_at) WHERE deleted_at IS NULL;
