-- Customer password reset tokens
-- Shared table used by both portal API (token generation) and customer API (token validation).
-- Portal staff triggers the reset; customer resets their password via the customer app.

CREATE TABLE IF NOT EXISTS customer_password_reset_tokens (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email        VARCHAR(255) NOT NULL,
    reset_code   VARCHAR(128) NOT NULL,   -- SHA-256 hash of the raw token
    expires_at   TIMESTAMP    NOT NULL,   -- 15 minutes from creation
    used         BOOLEAN      NOT NULL DEFAULT FALSE,
    created_at   TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_cust_pw_reset_email
    ON customer_password_reset_tokens (email);

CREATE INDEX IF NOT EXISTS idx_cust_pw_reset_expires_at
    ON customer_password_reset_tokens (expires_at);

CREATE INDEX IF NOT EXISTS idx_cust_pw_reset_used
    ON customer_password_reset_tokens (used);

CREATE INDEX IF NOT EXISTS idx_cust_pw_reset_email_code_used
    ON customer_password_reset_tokens (email, reset_code, used);
